"""rename Department

Revision ID: 41aa961deb00
Revises: b4c6c4b803ae
Create Date: 2025-10-01 16:53:30.882057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aa961deb00'
down_revision = 'b4c6c4b803ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
