"""rename colonne Department

Revision ID: 53db36e86408
Revises: 41aa961deb00
Create Date: 2025-10-01 17:00:25.958566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53db36e86408'
down_revision = '41aa961deb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
